### ISSUE TITLE
Unable to run the application from a local directory in terminal

### ISSUE THREAD

**Issue by KarthickRaja2002** [SourceCode-AI/aura#18]
In the document, it is stated that, if we haven't given the **URI in the input**, by default the AURA consider the **current local directory** as the input folder. I have tried this using the following command. 
`sudo docker run -ti --rm sourcecodeai/aura:dev scan file:///home/local/ZOHOCORP/karthick-pt5811/Downloads/hgtools-default`
But, it shows error as
`Invalid location provided from URI: 'file:///home/local/ZOHOCORP/karthick-pt5811/Downloads/hgtools-default`

Kindly fix it. @RootLUG

**Comment by RootLUG** [comment]
Hello @KarthickRaja2002,
From the command example you provided I can see that you are using Docker to run Aura. Docker container by default don't have any access to the files/paths on your computer so I would say the problem is in the incorrect usage and that file does not exist inside the container so Aura is not able to access it either.

If you want to scan the files inside the container you would first need to mount them as volume inside docker (the `-v` switch in docker cli), also be aware that when you mount a volume inside the docker, the path will be different from the one on your computer and must be adjusted accordingly.

**Comment by KarthickRaja2002** [comment]
Hello @RootLUG ,
Thank you for your reply.
Now I have tried by running **AURA locally using some local directory files**, it has run successfully and generated reports well.
The command I have used to run is given below.
`aura scan <file-name>`
