### ISSUE TITLE
Taint Analysis - Across file and class

### ISSUE THREAD

**Issue by KarthickRaja2002** [SourceCode-AI/aura#22]
@RootLUG ,

If source is on file **test1.py** (class A) and sink is in another file **test2.py** (class B), the user input passes from one file to another file, will it be considered as a **vulnerability**? In short, will it perform **_taint analysis across file and across class_**?

**Comment by RootLUG** [comment]
Hello @KarthickRaja2002 ,
yes and no. So there is already a partially implemented support for this but it is not fully functional for all use cases. Aura already contains some logic for this like doing an import sorting on input files so it can transfer the taints between the modules but this is not yet done for python modules in most cases due to performance reason, the code exists but it is not enabled/fully functional and is on a TODO list.
In some cases this is done and enabled so for example in flask taint analysis the taints are transfered from the route/view into the jinja template and continue there.
